name = "conject"
version = "0.1.0"
defaultTargets = ["Commons", "Statements", "Submissions", "Verify"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[lean_lib]]
name = "Commons"
globs = ["Commons.+"]

[[lean_lib]]
name = "Statements"
globs = ["Statements.+"]

[[lean_lib]]
name = "Submissions"
globs = ["Submissions.+"]

[[lean_lib]]
name = "Verify"
globs = ["Verify.+"]
