import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.Data.Fin.VecNotation
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Algebra.GCDMonoid.Finset

/-!
# ChainVolSymGammaOne — a balanced chain has a symmetric framing in `⋀²Γ₁ ⊗ ⋀²Γ₂`

Self-contained: imports only `Mathlib`, defines everything it mentions, uses no `Commons`.

## What this says

`KontsevichPhiIffContained` (p/8?s=17) reduces the root question to `Ξ_d ≤ ℤ⟨θ, w₁, w₂⟩`,
where `Ξ_d` is generated by `∑ᵢ cᵢ · cellVol(zᵢ)` over chains balanced against every
admissible `Ψ`.  This statement is the geometric half of that containment: **the class of a
balanced chain is an integral combination of the `36` products `(γ_p ∧ γ_q) · x_k`**, i.e. it
comes from `⋀²Γ₁ ⊗ ⋀²Γ₂` and not merely from `⋀²(Γ₂ ⊗ Γ_p) ⊗ ⋀²Γ₂`.

Two further conditions cut those `36` down to `3`: the framing symmetry (automatic on every
cell) and the Plücker relation (`ChainClassPlucker`).  The three together give
`Ξ_d ≤ ℤ⟨θ, w₁, w₂⟩` and hence, through s=17, the root.

## The argument, in full

Write `Λ = Γ₂ ⊗ Γ_p ≅ ℤ¹⁶` and `S = Sym²Γ_p ⊗ ⋀²Γ₂`, and let `π : Λ ∧ Λ → S` be `wedgeMat`
(the projection killing the `Sym²Γ₂ ⊗ ⋀²Γ_p` summand of `⋀²Λ`).  Set `Q = a·b·…` aside: none
of the steps below evaluates the parameters.

1. **Every cell class is a boundary pairing.**  For the triangle `(x, s, u, v)` put
   `p = u ⊗ s`, `q = v ⊗ s`; for the parallelogram `(x, s, t, u, v)` put `p = u ⊗ s`,
   `q = v ⊗ t`.  Then `cellVol = π(p ∧ q) · (u ∧ v)^` and `cellVol = 2 π(p ∧ q) · (u ∧ v)^`
   respectively — in both cases `cellVol = (2 · oriented area) ⊗ (framing)`.  Moreover the
   six (resp. eight) flags of `cellPhi` are exactly the endpoints of the three (resp. four)
   boundary edges: `∂T = -(x,p) + (x,q) + (x+q, p-q)` and
   `∂P = -(x,p) + (x+q,p) + (x,q) - (x+p,q)`, and for **any** alternating `Ω` on `Λ`,
   `∑_{∂cell} Ω(y, y') = -Ω(2·area)`.  (Shoelace; a `ring` identity.)

2. **Balancing is exactly the vanishing of the flag boundary.**  Instantiating the balancing
   hypothesis at `Ψ_F x u k = if ([x],[u]) = F then bv k else 0` — admissible, since it is
   `Γ₁`-periodic in `x` and invariant under `u ↦ m·u` — gives, for every flag class `F` and
   every `k`, `∑ᵢ cᵢ (u∧v)ᵢ[k] · n_F(zᵢ) = 0`.  So each `Γ₂`-component
   `Z_k = ∑ᵢ cᵢ (u∧v)ᵢ[k] · zᵢ` has zero boundary in the free group `D` on
   `(Λ/Γ₁) × (Γ₂ / scaling)`.

3. **What that kernel is.**  The boundary of the edge `(y, u⊗s)` is `[y+u⊗s] - [y]` in the
   `[u]`-component of `D`.  By `GammaOneRankOne` (p/8?s=16), `Γ₁` contains no nonzero
   rank-one element, so `s` is recovered from `[y]`, `[y+u⊗s]` and `[u]`, and the component
   of `D` at `[u]` is the vertex group of the Cayley graph of `Γ_p` with **all** nonzero
   elements as generators.  Its cycle space is generated by triangles, so
   `ker ∂` is generated by (a) `Γ₁`-translation differences `(y,r) - (y+γ,r)` and
   (b) concatenations `(y,u⊗s) + (y+u⊗s, u⊗s') - (y, u⊗(s+s'))`.

4. **The functionals that kill that kernel.**  Let `Γ₁^⊥ ⊆ Λ*` be the rank-`12` annihilator
   of `Γ₁` and let `Ω = ∑_α φ_α ∧ ψ_α` with every `ψ_α ∈ Γ₁^⊥`, subject also to
   `Ω(ker π) = 0`.  Put `g(y) = ∑_α φ_α(y) ψ_α(y)` and
   `J(y, y') = Ω(y, y') - g(y') + g(y)`.  Then
   * `J(y+γ, y'+γ) = J(y, y')` for `γ ∈ Γ₁` (uses `ψ_α|Γ₁ = 0`);
   * `J(y,z) + J(z,z') = J(y,z')` when `z-y` and `z'-z` are `u⊗s`, `u⊗s'` (uses
     `Ω((u⊗s) ∧ (u⊗s')) = 0`, which is `Ω(ker π) = 0`);
   * `∑_{∂cell} J = ∑_{∂cell} Ω` because `g` telescopes around the closed vertex loop.

   So `J` kills both generators of `ker ∂`, hence `Ω(2·area(Z_k)) = 0` for every such `Ω`.

5. **The annihilator is exactly `⋀²Γ₁`.**  Let `W = (Λ* ∧ Γ₁^⊥) ∩ Ann(ker π)`, read as a
   subgroup of `S*`.  A machine computation over `ℤ` (Hermite/Smith normal forms, no
   floating point) gives, for `d = 1, 2, 3`: `rank(Λ* ∧ Γ₁^⊥) = 114`, `rank Ann(ker π) = 60`,
   `rank W = 54`, and `{ξ ∈ S : W(ξ) = 0}` is a rank-`6` **saturated** sublattice equal to
   `⋀²Γ₁` on the nose — the six `π(γ_p ∧ γ_q)` expressed in a basis of that lattice have
   Smith normal form `[1,1,1,1,1,1]`.  So no index is lost and the conclusion is integral.

6. **The framing matrix is symmetric.**  This needs no balancing at all.  On a cell,
   `π(p ∧ q) = ŝ ŝ' · (u ∧ v)^`, so the `x_l`-coefficient of the `k`-th component of the
   class is `∑ᵢ cᵢ ŝᵢ ŝᵢ' βᵢ[k] βᵢ[l]`, visibly symmetric in `k` and `l`.  Since the six
   `γ_p ∧ γ_q` are `ℚ`-linearly independent in `S`, the coefficient matrix `n` produced by
   step 5 is the unique one, so it is this symmetric one: `∑ⱼ n k j · wcoef d j l` is
   symmetric in `k, l`.

7. Combining, `∑ᵢ cᵢ cellVol(zᵢ) = ∑_k (2·area(Z_k)) · x_k` with each `2·area(Z_k) ∈ ⋀²Γ₁`
   and the framing matrix symmetric, which is the displayed conclusion.

Step 5 is a finite integer computation; steps 1–4 are elementary algebra plus one appeal to
the already-green s=16.  Nothing here uses topology, real coefficients, or a choice of
fundamental domain.

## Read-back

* "balanced over admissible families" → the hypothesis, copied verbatim from the
  `chainClass` of s=17.
* "symmetric framing" → `∑ⱼ n k j · wcoef d j l = ∑ⱼ n l j · wcoef d j k` for all `k, l`.
  This conjunct is essential: without it the `36` coefficients are not determined by the
  class (the map `ℤ³⁶ → T` has a rank-`15` kernel, the antisymmetric framings) and the
  three-condition count below would be false.
* "class in `⋀²Γ₁ ⊗ ⋀²Γ₂`" → `∃ n : Fin 6 → Fin 6 → ℤ`, the class is
  `∑ₖ (∑ⱼ n k j · gm d j) · bv k`, where `gm d j = π(γ_{bivFst j} ∧ γ_{bivSnd j})` are the six
  generators of `⋀²Γ₁` and `bv k` the six of `⋀²Γ₂`.
* No primitivity hypothesis is imposed on the cells: the conclusion holds for every balanced
  chain.
-/

namespace Statements.ChainVolSymGammaOne

open MvPolynomial

abbrev T : Type := MvPolynomial (Fin 10) ℚ

/-- The four parameter variables `a, b, c, e`. -/
noncomputable def pv : Fin 4 → T := ![X 0, X 1, X 2, X 3]

/-- The six coordinates of `⋀²Γ₂`. -/
noncomputable def bv : Fin 6 → T := ![X 4, X 5, X 6, X 7, X 8, X 9]

abbrev G2 : Type := Fin 4 → ℤ
abbrev Gp : Type := Fin 4 → ℤ
abbrev G2P : Type := Fin 4 → Fin 4 → ℤ

def bivFst : Fin 6 → Fin 4 := ![0, 0, 0, 1, 1, 2]
def bivSnd : Fin 6 → Fin 4 := ![1, 2, 3, 2, 3, 3]

def wedge (u v : G2) (k : Fin 6) : ℤ :=
  u (bivFst k) * v (bivSnd k) - u (bivSnd k) * v (bivFst k)

noncomputable def wedgePoly (u v : G2) : T := ∑ k : Fin 6, ((wedge u v k : ℤ) : ℚ) • bv k
noncomputable def parPoly (s : Gp) : T := ∑ k : Fin 4, ((s k : ℤ) : ℚ) • pv k
noncomputable def rowPoly (A : G2P) (i : Fin 4) : T := ∑ m : Fin 4, ((A i m : ℤ) : ℚ) • pv m

/-- The projection of `A ∧ B` to `Sym²Γ_p ⊗ ⋀²Γ₂`. -/
noncomputable def wedgeMat (A B : G2P) : T :=
  ∑ k : Fin 6,
    (rowPoly A (bivFst k) * rowPoly B (bivSnd k) - rowPoly A (bivSnd k) * rowPoly B (bivFst k))
      * bv k

def gammaGen (d : ℤ) : Fin 4 → G2P :=
  ![ ![![1, 0, 0, 0], ![0, 1, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 1]],
     ![![0, 1, 0, 0], ![0, 0, 1, 0], ![0, 0, 0, -1], ![0, 0, 0, 0]],
     ![![0, 0, 0, 0], ![0, 0, 0, -1], ![d, 0, 0, 0], ![0, d, 0, 0]],
     ![![0, 0, 0, 1], ![0, 0, 0, 0], ![0, d, 0, 0], ![0, 0, d, 0]] ]

noncomputable def gammaOne (d : ℤ) : Submodule ℤ G2P :=
  Submodule.span ℤ (Set.range (gammaGen d))

/-- The `x_l`-coefficient of `γ_{bivFst j} ∧ γ_{bivSnd j}`: the `2×2` minor of the
polarisation matrix on rows `{bivFst j, bivSnd j}` and columns `{bivFst l, bivSnd l}`. -/
noncomputable def wcoef (d : ℤ) (j l : Fin 6) : T :=
  rowPoly (gammaGen d (bivFst j)) (bivFst l) * rowPoly (gammaGen d (bivSnd j)) (bivSnd l)
    - rowPoly (gammaGen d (bivFst j)) (bivSnd l) * rowPoly (gammaGen d (bivSnd j)) (bivFst l)

/-- The six generators `γ_p ∧ γ_q` of `⋀²Γ₁`, in `Sym²Γ_p ⊗ ⋀²Γ₂`.  By construction
`gm d j = ∑_l wcoef d j l · bv l`. -/
noncomputable def gm (d : ℤ) (j : Fin 6) : T :=
  wedgeMat (gammaGen d (bivFst j)) (gammaGen d (bivSnd j))

def outer (u : G2) (s : Gp) : G2P := fun i k => u i * s k

noncomputable def app (Φ : G2P → G2 → Fin 6 → T) (x : G2P) (u : G2) (β : Fin 6 → ℤ) : T :=
  ∑ k : Fin 6, ((β k : ℤ) : ℚ) • Φ x u k

abbrev TriInst : Type := G2P × Gp × G2 × G2
abbrev ParInst : Type := G2P × Gp × Gp × G2 × G2

noncomputable def triPhi (Φ : G2P → G2 → Fin 6 → T) (e : TriInst) : T :=
  app Φ e.1 e.2.2.1 (wedge e.2.2.1 e.2.2.2) - app Φ e.1 e.2.2.2 (wedge e.2.2.1 e.2.2.2)
    + app Φ (e.1 + outer e.2.2.1 e.2.1) (e.2.2.1 - e.2.2.2) (wedge e.2.2.1 e.2.2.2)
    - app Φ (e.1 + outer e.2.2.1 e.2.1) e.2.2.1 (wedge e.2.2.1 e.2.2.2)
    + app Φ (e.1 + outer e.2.2.2 e.2.1) e.2.2.2 (wedge e.2.2.1 e.2.2.2)
    - app Φ (e.1 + outer e.2.2.2 e.2.1) (e.2.2.1 - e.2.2.2) (wedge e.2.2.1 e.2.2.2)

noncomputable def triRHS (e : TriInst) : T :=
  parPoly e.2.1 ^ 2 * wedgePoly e.2.2.1 e.2.2.2 ^ 2

noncomputable def parPhi (Φ : G2P → G2 → Fin 6 → T) (e : ParInst) : T :=
  app Φ e.1 e.2.2.2.1 (wedge e.2.2.2.1 e.2.2.2.2)
    - app Φ e.1 e.2.2.2.2 (wedge e.2.2.2.1 e.2.2.2.2)
    + app Φ (e.1 + outer e.2.2.2.1 e.2.1) e.2.2.2.2 (wedge e.2.2.2.1 e.2.2.2.2)
    - app Φ (e.1 + outer e.2.2.2.1 e.2.1) e.2.2.2.1 (wedge e.2.2.2.1 e.2.2.2.2)
    - app Φ (e.1 + outer e.2.2.2.2 e.2.2.1) e.2.2.2.1 (wedge e.2.2.2.1 e.2.2.2.2)
    + app Φ (e.1 + outer e.2.2.2.2 e.2.2.1) e.2.2.2.2 (wedge e.2.2.2.1 e.2.2.2.2)
    + app Φ (e.1 + outer e.2.2.2.1 e.2.1 + outer e.2.2.2.2 e.2.2.1) e.2.2.2.1
        (wedge e.2.2.2.1 e.2.2.2.2)
    - app Φ (e.1 + outer e.2.2.2.1 e.2.1 + outer e.2.2.2.2 e.2.2.1) e.2.2.2.2
        (wedge e.2.2.2.1 e.2.2.2.2)

noncomputable def parRHS (e : ParInst) : T :=
  (2 : ℚ) • (parPoly e.2.1 * parPoly e.2.2.1 * wedgePoly e.2.2.2.1 e.2.2.2.2 ^ 2)

abbrev Cell : Type := TriInst ⊕ ParInst

noncomputable def cellPhi (Φ : G2P → G2 → Fin 6 → T) : Cell → T
  | Sum.inl e => triPhi Φ e
  | Sum.inr e => parPhi Φ e

noncomputable def cellVol : Cell → T
  | Sum.inl e => triRHS e
  | Sum.inr e => parRHS e

/-- `Γ₁`-periodic in the vertex, invariant under nonzero integer rescaling of the direction. -/
def Admissible (d : ℤ) (Ψ : G2P → G2 → Fin 6 → T) : Prop :=
  (∀ (x : G2P) (u : G2) (g : G2P), g ∈ gammaOne d → Ψ (x + g) u = Ψ x u) ∧
    (∀ (x : G2P) (u : G2) (m : ℤ), m ≠ 0 → Ψ x (m • u) = Ψ x u)

/-- The canonical proposition.  This is the type the verifier demands.

For every `d > 0`, the tautological class of a chain balanced over all admissible families is
an integral combination of the `36` classes `(γ_p ∧ γ_q) ⊗ e_k` — i.e. it lies in the image
of `⋀²Γ₁ ⊗ ⋀²Γ₂` — **by a coefficient matrix `n` whose framing matrix `n · wcoef` is
symmetric**. -/
abbrev statement : Prop :=
  ∀ (d : ℤ), 0 < d →
    ∀ (ι : Type) (s : Finset ι) (c : ι → ℤ) (z : ι → Cell),
      (∀ Ψ : G2P → G2 → Fin 6 → T, Admissible d Ψ →
          ∑ i ∈ s, (c i : T) * cellPhi Ψ (z i) = 0) →
      ∃ n : Fin 6 → Fin 6 → ℤ,
        (∀ k l : Fin 6,
            ∑ j : Fin 6, (n k j : T) * wcoef d j l = ∑ j : Fin 6, (n l j : T) * wcoef d j k) ∧
          ∑ i ∈ s, (c i : T) * cellVol (z i)
            = ∑ k : Fin 6, (∑ j : Fin 6, (n k j : T) * gm d j) * bv k

/-- The open target.  A submission proves `statement` in its own module; the verifier bridges
the two. -/
theorem target : statement := sorry

end Statements.ChainVolSymGammaOne
