import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.Data.Fin.VecNotation
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Algebra.GCDMonoid.Finset

/-!
# ChainClassPlucker — every tautological chain class satisfies the Plücker relation

Self-contained: imports only `Mathlib`, defines everything it mentions, uses no `Commons`.

## What this says

Zharkov's right-hand sides are `s² ⊗ (u ∧ v)²` (triangle) and `2st ⊗ (u ∧ v)²`
(parallelogram): in each of them the `Sym²(⋀²Γ₂)` factor is the **square of a decomposable
bivector** `β = u ∧ v`.  A decomposable bivector satisfies the Plücker (Pfaffian) relation
`β₁₂β₃₄ - β₁₃β₂₄ + β₁₄β₂₃ = 0`, so the associated quadratic form on `⋀²Γ₂` is degenerate in
exactly that one way, for every cell, with no hypothesis on the cell whatsoever.

`plucker` below is the linear functional that reads off
`coeff(x₁₂x₃₄) - coeff(x₁₃x₂₄) + coeff(x₁₄x₂₃)` at a rational parameter point `p`, as a
combination of ten evaluations, so that it needs no `MvPolynomial.coeff` API.  On a
`(2,2)`-form `q · (∑ β_k x_k)²` with `q` of `x`-degree `0` it returns `2 q(p) Pf(β)`.

The statement is that `plucker` kills the tautological class of **every** finite chain of
cells: no balancing, no primitivity, no positivity.  Since `plucker` is `ℚ`-linear this is a
cell-by-cell fact, but it is the useful form: it is one of the three linear conditions that
cut the `36`-dimensional lattice `⋀²Γ₁ ⊗ ⋀²Γ₂` down to `ℤ⟨θ, w₁, w₂⟩`.

## Why it is worth having

`KontsevichPhiIffContained` (p/8?s=17) reduces the root question to `Ξ_d ≤ ℤ⟨θ, w₁, w₂⟩`,
where `Ξ_d` is generated by the tautological classes of chains balanced over admissible
families.  `plucker` vanishes on all of `Ξ_d` by this statement, and `plucker` does **not**
vanish on the fourth direction of the space of symmetric elements of `⋀²Γ₁ ⊗ ⋀²Γ₂` — so this
is one of the two conditions (the other being the symmetry of the framing) that, together
with membership in `⋀²Γ₁ ⊗ ⋀²Γ₂`, pin `Ξ_d` inside the Weil lattice.  Nothing here uses or
asserts that membership; that is a separate obligation.

## Read-back

* "tautological class of a chain" → `∑ i ∈ s, (c i : T) * cellVol (z i)`, with `cellVol` the
  right-hand sides of Zharkov's (1) and (2), transcribed as in the root statement.
* "the Plücker relation" → `plucker` applied to that class is `0`.
* No hypothesis: `ι`, `s`, `c`, `z` are arbitrary.
-/

namespace Statements.ChainClassPlucker

open MvPolynomial

/-- `Sym²Γ_p ⊗ Sym²(⋀²Γ₂)` as the bidegree-`(2,2)` part of this ring. -/
abbrev T : Type := MvPolynomial (Fin 10) ℚ

/-- The four parameter variables `a, b, c, e`. -/
noncomputable def pv : Fin 4 → T := ![X 0, X 1, X 2, X 3]

/-- The six coordinates `x₁₂, x₁₃, x₁₄, x₂₃, x₂₄, x₃₄` of `⋀²Γ₂`. -/
noncomputable def bv : Fin 6 → T := ![X 4, X 5, X 6, X 7, X 8, X 9]

/-- The lattice `Γ₂` of integral slopes. -/
abbrev G2 : Type := Fin 4 → ℤ

/-- The parameter lattice `Γ_p`. -/
abbrev Gp : Type := Fin 4 → ℤ

/-- `Γ₂ ⊗ Γ_p`. -/
abbrev G2P : Type := Fin 4 → Fin 4 → ℤ

/-- First index of the `k`-th basis bivector. -/
def bivFst : Fin 6 → Fin 4 := ![0, 0, 0, 1, 1, 2]

/-- Second index of the `k`-th basis bivector. -/
def bivSnd : Fin 6 → Fin 4 := ![1, 2, 3, 2, 3, 3]

/-- Coordinates of `u ∧ v ∈ ⋀²Γ₂`. -/
def wedge (u v : G2) (k : Fin 6) : ℤ :=
  u (bivFst k) * v (bivSnd k) - u (bivSnd k) * v (bivFst k)

/-- `u ∧ v` as a linear form in the `⋀²Γ₂` coordinates. -/
noncomputable def wedgePoly (u v : G2) : T := ∑ k : Fin 6, ((wedge u v k : ℤ) : ℚ) • bv k

/-- `s ∈ Γ_p` as a linear form in the parameters. -/
noncomputable def parPoly (s : Gp) : T := ∑ k : Fin 4, ((s k : ℤ) : ℚ) • pv k

/-- A triangle instance: vertex, parameter vector, two directions. -/
abbrev TriInst : Type := G2P × Gp × G2 × G2

/-- A parallelogram instance: vertex, two parameter vectors, two directions. -/
abbrev ParInst : Type := G2P × Gp × Gp × G2 × G2

/-- The right-hand side of Zharkov's triangle relation (1): `s² ⊗ (u ∧ v)²`. -/
noncomputable def triRHS (e : TriInst) : T :=
  parPoly e.2.1 ^ 2 * wedgePoly e.2.2.1 e.2.2.2 ^ 2

/-- The right-hand side of Zharkov's parallelogram relation (2): `2st ⊗ (u ∧ v)²`. -/
noncomputable def parRHS (e : ParInst) : T :=
  (2 : ℚ) • (parPoly e.2.1 * parPoly e.2.2.1 * wedgePoly e.2.2.2.1 e.2.2.2.2 ^ 2)

/-- One cell of a chain: a triangle or a parallelogram. -/
abbrev Cell : Type := TriInst ⊕ ParInst

/-- The tautological class of a cell. -/
noncomputable def cellVol : Cell → T
  | Sum.inl e => triRHS e
  | Sum.inr e => parRHS e

/-! ## The Plücker functional -/

/-- Evaluate at a rational point: the parameters at `p`, the six `⋀²Γ₂` coordinates at
`m₀ … m₅`. -/
noncomputable def evp (p : Fin 4 → ℚ) (m0 m1 m2 m3 m4 m5 : ℚ) : T →ₐ[ℚ] ℚ :=
  MvPolynomial.aeval ![p 0, p 1, p 2, p 3, m0, m1, m2, m3, m4, m5]

/-- `coeff(x₁₂x₃₄) - coeff(x₁₃x₂₄) + coeff(x₁₄x₂₃)`, read off at the parameter point `p` as a
second difference of `evp` in each of the three complementary pairs of coordinates.  On a
`(2,2)`-form `q · (∑ β_k x_k)²` with `q` free of the `x`'s it returns `2 q(p) Pf(β)`. -/
noncomputable def plucker (p : Fin 4 → ℚ) (f : T) : ℚ :=
  (evp p 1 0 0 0 0 1 f - evp p 1 0 0 0 0 0 f - evp p 0 0 0 0 0 1 f + evp p 0 0 0 0 0 0 f)
    - (evp p 0 1 0 0 1 0 f - evp p 0 1 0 0 0 0 f - evp p 0 0 0 0 1 0 f + evp p 0 0 0 0 0 0 f)
    + (evp p 0 0 1 1 0 0 f - evp p 0 0 1 0 0 0 f - evp p 0 0 0 1 0 0 f + evp p 0 0 0 0 0 0 f)

/-- The canonical proposition.  This is the type the verifier demands.

At every rational parameter point, the Plücker functional annihilates the tautological class
of every finite chain of cells — with no balancing, primitivity or positivity hypothesis. -/
abbrev statement : Prop :=
  ∀ (p : Fin 4 → ℚ) (ι : Type) (s : Finset ι) (c : ι → ℤ) (z : ι → Cell),
    plucker p (∑ i ∈ s, (c i : T) * cellVol (z i)) = 0

/-- The open target.  A submission proves `statement` in its own module; the verifier bridges
the two. -/
theorem target : statement := sorry

end Statements.ChainClassPlucker
