import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.Data.Fin.VecNotation
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Algebra.GCDMonoid.Finset

/-!
# GammaOneSymPluckerLattice — symmetry plus Plücker cuts `⋀²Γ₁ ⊗ ⋀²Γ₂` down to `ℤ⟨θ,w₁,w₂⟩`

Self-contained: imports only `Mathlib`, defines everything it mentions, uses no `Commons`.

## What this says

At `d = 1`, an element of `⋀²Γ₁ ⊗ ⋀²Γ₂` is `36` integers `n k j` — the coefficient of
`(γ_{bivFst j} ∧ γ_{bivSnd j}) ⊗ e_k`.  Its **framing matrix** is
`S k l = ∑_j n k j · wcoef 1 j l`, where `wcoef 1 j l` is the `2×2` minor of the polarisation
matrix `Q` on rows `{bivFst j, bivSnd j}` and columns `{bivFst l, bivSnd l}`, so that the
class as a polynomial is `∑_{k,l} S k l · x_l x_k`.

Two linear conditions on `S`:

* **symmetry** `S k l = S l k` — automatic for the class of any chain of cells, because on a
  cell the class is `(quadratic in the parameters) · β_k β_l` with `β = u ∧ v`;
* **Plücker** `S 0 5 - S 1 4 + S 2 3 = 0` — which, given symmetry, is exactly half of the
  functional `plucker` of `ChainClassPlucker` (p/8?s=19) applied to the class, since
  `plucker` returns `(S 0 5 + S 5 0) - (S 1 4 + S 4 1) + (S 2 3 + S 3 2)`.

The conclusion is that the class then lies in `ℤ⟨θ, w₁, w₂⟩` — **integrally**, with no index
lost.  The rank drops `36 → 3` and the resulting rank-`3` lattice is the Weil lattice on the
nose: the three solutions

  `n = I` (identity) `↦ θ`,
  `n = E₀₀ - E₀₅ - E₂₂ + E₂₃ + E₃₂ - E₃₃ - E₅₀ + E₅₅ ↦ w₁`,
  `n = E₀₂ - E₀₃ + E₂₀ - E₂₅ - E₃₀ + E₃₅ - E₅₂ + E₅₃ ↦ w₂`

span the full integral solution set (Hermite normal form check).

## Why it is worth having

`KontsevichPhiIffContained` (p/8?s=17) makes the root question exactly
`Ξ_d ≤ ℤ⟨θ, w₁, w₂⟩`.  `ChainVolSymGammaOne` (p/8?s=21) says a balanced chain class is such an
`n` with symmetric framing; `ChainClassPlucker` (p/8?s=19) supplies the Plücker condition.
This statement is the third leg: it converts those two conditions into membership in the Weil
lattice.  s=19 ∧ s=21 ∧ this ⟹ `Ξ_1 ≤ weilLattice 1` ⟹ (s=17) the root.

## Read-back

* "an element of `⋀²Γ₁ ⊗ ⋀²Γ₂`" → `n : Fin 6 → Fin 6 → ℤ`, class `∑ₖ (∑ⱼ n k j · gm 1 j) · x_k`.
* "framing symmetric" → the first hypothesis, an identity in the parameters.
* "Plücker" → the second hypothesis, likewise an identity in the parameters.
* "lies in `ℤ⟨θ, w₁, w₂⟩`" → membership in `weilLattice 1`, a `ℤ`-span.
* Only `d = 1` is treated; that is the case the endgame needs.  For `d ≥ 2` the same
  computation gives the index-`d` sublattice generated by `θ`, `w₂` and `d(θ - w₁)`, still
  inside the Weil lattice, but that is not claimed here.
-/

namespace Statements.GammaOneSymPluckerLattice

open MvPolynomial

abbrev T : Type := MvPolynomial (Fin 10) ℚ

noncomputable def pv : Fin 4 → T := ![X 0, X 1, X 2, X 3]
noncomputable def bv : Fin 6 → T := ![X 4, X 5, X 6, X 7, X 8, X 9]

abbrev G2 : Type := Fin 4 → ℤ
abbrev Gp : Type := Fin 4 → ℤ
abbrev G2P : Type := Fin 4 → Fin 4 → ℤ

def bivFst : Fin 6 → Fin 4 := ![0, 0, 0, 1, 1, 2]
def bivSnd : Fin 6 → Fin 4 := ![1, 2, 3, 2, 3, 3]

noncomputable def rowPoly (A : G2P) (i : Fin 4) : T := ∑ m : Fin 4, ((A i m : ℤ) : ℚ) • pv m

noncomputable def wedgeMat (A B : G2P) : T :=
  ∑ k : Fin 6,
    (rowPoly A (bivFst k) * rowPoly B (bivSnd k) - rowPoly A (bivSnd k) * rowPoly B (bivFst k))
      * bv k

def gammaGen (d : ℤ) : Fin 4 → G2P :=
  ![ ![![1, 0, 0, 0], ![0, 1, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 1]],
     ![![0, 1, 0, 0], ![0, 0, 1, 0], ![0, 0, 0, -1], ![0, 0, 0, 0]],
     ![![0, 0, 0, 0], ![0, 0, 0, -1], ![d, 0, 0, 0], ![0, d, 0, 0]],
     ![![0, 0, 0, 1], ![0, 0, 0, 0], ![0, d, 0, 0], ![0, 0, d, 0]] ]

/-- The `x_l`-coefficient of `γ_{bivFst j} ∧ γ_{bivSnd j}`. -/
noncomputable def wcoef (d : ℤ) (j l : Fin 6) : T :=
  rowPoly (gammaGen d (bivFst j)) (bivFst l) * rowPoly (gammaGen d (bivSnd j)) (bivSnd l)
    - rowPoly (gammaGen d (bivFst j)) (bivSnd l) * rowPoly (gammaGen d (bivSnd j)) (bivFst l)

/-- The six generators of `⋀²Γ₁`, in `Sym²Γ_p ⊗ ⋀²Γ₂`. -/
noncomputable def gm (d : ℤ) (j : Fin 6) : T :=
  wedgeMat (gammaGen d (bivFst j)) (gammaGen d (bivSnd j))

noncomputable def theta (d : ℤ) : T :=
  ∑ k : Fin 6, wedgeMat (gammaGen d (bivFst k)) (gammaGen d (bivSnd k)) * bv k

noncomputable def w1 (d : ℤ) : T :=
  let g := gammaGen d
  wedgeMat (g 0) (g 1) * bv 0
    - (1 / (d : ℚ)) • (wedgeMat (g 2) (g 3) * bv 0)
    - wedgeMat (g 0) (g 3) * bv 2
    + wedgeMat (g 0) (g 3) * bv 3
    + wedgeMat (g 1) (g 2) * bv 2
    - wedgeMat (g 1) (g 2) * bv 3
    - (d : ℚ) • (wedgeMat (g 0) (g 1) * bv 5)
    + wedgeMat (g 2) (g 3) * bv 5

noncomputable def w2 (d : ℤ) : T :=
  let g := gammaGen d
  wedgeMat (g 0) (g 3) * bv 0
    - (d : ℚ) • (wedgeMat (g 0) (g 3) * bv 5)
    - (d : ℚ) • (wedgeMat (g 0) (g 1) * bv 3)
    + wedgeMat (g 2) (g 3) * bv 3
    + (d : ℚ) • (wedgeMat (g 0) (g 1) * bv 2)
    - wedgeMat (g 2) (g 3) * bv 2
    - wedgeMat (g 1) (g 2) * bv 0
    + (d : ℚ) • (wedgeMat (g 1) (g 2) * bv 5)

noncomputable def weilLattice (d : ℤ) : Submodule ℤ T :=
  Submodule.span ℤ {theta d, w1 d, w2 d}

/-- The canonical proposition.  This is the type the verifier demands.

At `d = 1`: if the framing matrix of an integral element of `⋀²Γ₁ ⊗ ⋀²Γ₂` is symmetric and
satisfies the Plücker relation, then its class lies in `ℤ⟨θ, w₁, w₂⟩`. -/
abbrev statement : Prop :=
  ∀ n : Fin 6 → Fin 6 → ℤ,
    (∀ k l : Fin 6,
        ∑ j : Fin 6, (n k j : T) * wcoef 1 j l = ∑ j : Fin 6, (n l j : T) * wcoef 1 j k) →
    (∑ j : Fin 6, (n 0 j : T) * wcoef 1 j 5 - ∑ j : Fin 6, (n 1 j : T) * wcoef 1 j 4
        + ∑ j : Fin 6, (n 2 j : T) * wcoef 1 j 3 = 0) →
    (∑ k : Fin 6, (∑ j : Fin 6, (n k j : T) * gm 1 j) * bv k) ∈ weilLattice 1

/-- The open target.  A submission proves `statement` in its own module; the verifier bridges
the two. -/
theorem target : statement := sorry

end Statements.GammaOneSymPluckerLattice
