import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.Data.Fin.VecNotation
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Algebra.GCDMonoid.Finset

/-!
# KontsevichVolParity — a parity obstruction on integral tautological classes

Self-contained: imports only `Mathlib`, defines everything it mentions, uses no `Commons`.

## What this says

Zharkov's tautological map sends a triangle to `s² ⊗ (u ∧ v)²` and a parallelogram to
`2st ⊗ (u ∧ v)²`.  The first is a **square**; the second is **even**.  So modulo `2` the class
of any `ℤ`-combination of triangles and parallelograms is a square, by the Frobenius identity
`(f + g)² = f² + g²` in characteristic `2`.

The square of the polarisation `θ` is not a square modulo `2`, and neither is `w₁`.  Hence
**neither `θ` nor `w₁` is the tautological class of any chain** of triangles and parallelograms
with vertices in `Γ₂ ⊗ Γ_p` — balanced or not, and for every `d`.  More precisely, if a chain's
class lies in `ℤ⟨θ, w₁, w₂⟩` and equals `n₁θ + n₂w₁ + n₃w₂`, then `n₁ + n₂` is even.

The proof needs no characteristic-`2` machinery.  Let `ψ_{ε,η}` evaluate

  `a ↦ ε,  c ↦ η,  x₁₂ ↦ 1,  b, e, x₁₃, x₁₄, x₂₃, x₂₄, x₃₄ ↦ 0`,

and let `Δ f := ψ_{1,1} f - ψ_{1,0} f - ψ_{0,1} f + ψ_{0,0} f` be the mixed second difference in
`(ε, η)`, which reads off the coefficient of `a·c`.  Then

  `Δ (s² ⊗ (u∧v)²) = 2 s₁ s₃ (u∧v)₁₂²`,     `Δ (2st ⊗ (u∧v)²) = 2 (s₁t₃ + s₃t₁) (u∧v)₁₂²`,

both even, while `Δ θ = Δ w₁ = 1` and `Δ w₂ = 0`, for every `d`.

## Why it sits on this problem

The root statement asks for `Φ` with all defects in a **proper** sublattice `L` of
`ℤ⟨θ, w₁, w₂⟩`.  Soundness (`KontsevichPhiSoundness`) says such an `L` must contain the class
of every balanced chain; so the group `Λ` of balanced-chain classes is the minimal candidate
for `L`.  This statement shows `θ ∉ Λ` and `w₁ ∉ Λ`, hence `Λ ≠ ℤ⟨θ, w₁, w₂⟩`.  Combined with
`KontsevichPhiComplete`, the root statement is therefore equivalent to the single remaining
question `Λ ⊆ ℤ⟨θ, w₁, w₂⟩`.

It also explains, and sharpens, a remark of Zharkov's.  He writes that `θ` is algebraic, and
separately that subdividing a lattice polygon into triangles and parallelograms may introduce
rational vertices, so that "we may need to tensor everything with `ℚ`".  Those two remarks are
in tension over `ℤ`, and this resolves the tension in favour of the second: `θ` is algebraic
**rationally**, and integrally it is not even in the group generated by all cell classes.

## The consequence for the Hodge conjecture, stated so it cannot be misread

A proper sublattice of finite index is still proper.  So an `L` witnessing the root statement
may fail to contain `θ` for this parity reason alone, and the Hodge class it then leaves
unrepresented is unrepresented only by **integral** cycles.  The Hodge conjecture is a
statement with `ℚ` coefficients, so such an `L` refutes nothing about it.  For Kontsevich's
scheme to reach the Hodge conjecture one needs the strictly stronger conclusion that `L ⊗ ℚ`
is a proper subspace of `ℚ⟨θ, w₁, w₂⟩`, which the root statement as posed does not ask for.
This statement does not decide the root question either way; it says what a positive answer
would and would not buy.

## What is not claimed

Nothing about whether `Λ ⊆ ℤ⟨θ, w₁, w₂⟩`, nothing about `2θ`, `4θ` or any other multiple
(indeed `Δ (2θ) = 2` is even, so this obstruction says nothing against them), and nothing
about balanced chains specifically: the statement is about **all** chains, which is why no
balancing hypothesis appears.
-/

namespace Statements.KontsevichVolParity

open MvPolynomial

/-- `Sym²Γ_p ⊗ Sym²(⋀²Γ₂)` realised as the bidegree-`(2,2)` part of this polynomial ring:
`X 0 … X 3` are the parameters `a, b, c, e`; `X 4 … X 9` are `x₁₂, x₁₃, x₁₄, x₂₃, x₂₄, x₃₄`. -/
abbrev T : Type := MvPolynomial (Fin 10) ℚ

noncomputable def pv : Fin 4 → T := ![X 0, X 1, X 2, X 3]
noncomputable def bv : Fin 6 → T := ![X 4, X 5, X 6, X 7, X 8, X 9]

abbrev G2 : Type := Fin 4 → ℤ
abbrev Gp : Type := Fin 4 → ℤ
abbrev G2P : Type := Fin 4 → Fin 4 → ℤ

def bivFst : Fin 6 → Fin 4 := ![0, 0, 0, 1, 1, 2]
def bivSnd : Fin 6 → Fin 4 := ![1, 2, 3, 2, 3, 3]

def wedge (u v : G2) (k : Fin 6) : ℤ :=
  u (bivFst k) * v (bivSnd k) - u (bivSnd k) * v (bivFst k)

noncomputable def wedgePoly (u v : G2) : T := ∑ k : Fin 6, ((wedge u v k : ℤ) : ℚ) • bv k
noncomputable def parPoly (s : Gp) : T := ∑ k : Fin 4, ((s k : ℤ) : ℚ) • pv k
noncomputable def rowPoly (A : G2P) (i : Fin 4) : T := ∑ m : Fin 4, ((A i m : ℤ) : ℚ) • pv m

/-- The projection of `A ∧ B ∈ ⋀²(Γ₂ ⊗ Γ_p)` to `Sym²Γ_p ⊗ ⋀²Γ₂`. -/
noncomputable def wedgeMat (A B : G2P) : T :=
  ∑ k : Fin 6,
    (rowPoly A (bivFst k) * rowPoly B (bivSnd k) - rowPoly A (bivSnd k) * rowPoly B (bivFst k))
      * bv k

/-- The four columns of Zharkov's polarisation matrix `Q`, read in `Γ₂ ⊗ Γ_p`. -/
def gammaGen (d : ℤ) : Fin 4 → G2P :=
  ![ ![![1, 0, 0, 0], ![0, 1, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 1]],
     ![![0, 1, 0, 0], ![0, 0, 1, 0], ![0, 0, 0, -1], ![0, 0, 0, 0]],
     ![![0, 0, 0, 0], ![0, 0, 0, -1], ![d, 0, 0, 0], ![0, d, 0, 0]],
     ![![0, 0, 0, 1], ![0, 0, 0, 0], ![0, d, 0, 0], ![0, 0, d, 0]] ]

/-- `θ = Σ_{i<j} γ_{ij} ⊗ e_{ij}`, the square of the polarisation. -/
noncomputable def theta (d : ℤ) : T :=
  ∑ k : Fin 6, wedgeMat (gammaGen d (bivFst k)) (gammaGen d (bivSnd k)) * bv k

/-- The first Weil class. -/
noncomputable def w1 (d : ℤ) : T :=
  let g := gammaGen d
  wedgeMat (g 0) (g 1) * bv 0
    - (1 / (d : ℚ)) • (wedgeMat (g 2) (g 3) * bv 0)
    - wedgeMat (g 0) (g 3) * bv 2
    + wedgeMat (g 0) (g 3) * bv 3
    + wedgeMat (g 1) (g 2) * bv 2
    - wedgeMat (g 1) (g 2) * bv 3
    - (d : ℚ) • (wedgeMat (g 0) (g 1) * bv 5)
    + wedgeMat (g 2) (g 3) * bv 5

/-- The second Weil class. -/
noncomputable def w2 (d : ℤ) : T :=
  let g := gammaGen d
  wedgeMat (g 0) (g 3) * bv 0
    - (d : ℚ) • (wedgeMat (g 0) (g 3) * bv 5)
    - (d : ℚ) • (wedgeMat (g 0) (g 1) * bv 3)
    + wedgeMat (g 2) (g 3) * bv 3
    + (d : ℚ) • (wedgeMat (g 0) (g 1) * bv 2)
    - wedgeMat (g 2) (g 3) * bv 2
    - wedgeMat (g 1) (g 2) * bv 0
    + (d : ℚ) • (wedgeMat (g 1) (g 2) * bv 5)

/-- A triangle instance: vertex, parameter vector, two directions. -/
abbrev TriInst : Type := G2P × Gp × G2 × G2

/-- A parallelogram instance: vertex, two parameter vectors, two directions. -/
abbrev ParInst : Type := G2P × Gp × Gp × G2 × G2

/-- The tautological class of a triangle: `s² ⊗ (u ∧ v)²`. -/
noncomputable def triRHS (e : TriInst) : T :=
  parPoly e.2.1 ^ 2 * wedgePoly e.2.2.1 e.2.2.2 ^ 2

/-- The tautological class of a parallelogram: `2st ⊗ (u ∧ v)²`. -/
noncomputable def parRHS (e : ParInst) : T :=
  (2 : ℚ) • (parPoly e.2.1 * parPoly e.2.2.1 * wedgePoly e.2.2.2.1 e.2.2.2.2 ^ 2)

/-- One cell of a chain: a triangle or a parallelogram. -/
abbrev Cell : Type := TriInst ⊕ ParInst

/-- The tautological class of a cell. -/
noncomputable def cellVol : Cell → T
  | Sum.inl e => triRHS e
  | Sum.inr e => parRHS e

/-- The canonical proposition.  This is the type the verifier demands.

If a `ℤ`-combination of tautological classes of triangles and parallelograms lies in
`ℤ⟨θ, w₁, w₂⟩` and is written `n₁θ + n₂w₁ + n₃w₂`, then `n₁ + n₂` is even.  In particular
neither `θ` nor `w₁` is the tautological class of any such chain, for any `d`. -/
abbrev statement : Prop :=
  ∀ (d : ℤ) (ι : Type) (s : Finset ι) (c : ι → ℤ) (z : ι → Cell) (n₁ n₂ n₃ : ℤ),
    ∑ i ∈ s, (c i : T) * cellVol (z i)
        = (n₁ : T) * theta d + (n₂ : T) * w1 d + (n₃ : T) * w2 d →
      Even (n₁ + n₂)

/-- The open target.  A submission proves `statement` in its own module; the verifier
bridges the two. -/
theorem target : statement := sorry

end Statements.KontsevichVolParity
