import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.Data.Fin.VecNotation
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Algebra.GCDMonoid.Finset

/-!
# KontsevichPhiCompleteness — is Kontsevich's certificate complete?

Self-contained: imports only `Mathlib`, defines everything it mentions, uses no `Commons`.

## What this asks

`KontsevichPhiSoundnessPeriodic` proves one direction: an admissible `Φ` with defects in `L`
forces every chain balanced over admissible families to have tautological class in `L`.  This
statement asks for the **converse**: if `L` contains the class of every such chain, does an
admissible `Φ` with defects in `L` exist?

`KontsevichPhiSoundness` (green on this problem) explicitly declines to claim this and says it
is not believed to follow, on the ground that "extending the assignment from the subgroup
generated by the equation vectors to the whole flag module can be obstructed".

## Why the answer is decisive for the root statement

Together with soundness, a yes here turns the root statement into a lattice computation with
no gap in either direction.  Write

  `Ξ_d := { tautological classes of chains balanced over admissible families }`,

a subgroup of `MvPolynomial (Fin 10) ℚ`.  Soundness says a `Φ` modulo `L` forces `Ξ_d ⊆ L`;
completeness says `Ξ_d ⊆ L` suffices.  The root statement — some `d > 0` admits a proper
sublattice `L < ℤ⟨θ, w₁, w₂⟩` and an admissible `Φ` with defects in `L` — therefore becomes,
exactly,

  **`∃ d > 0` with `⟨Ξ_d⟩` a proper subgroup of `ℤ⟨θ(d), w₁(d), w₂(d)⟩`**,

taking `L = ⟨Ξ_d⟩`.  In words: Kontsevich's certificate exists if and only if the tautological
classes of tropical cycles do not generate the full lattice of tropical Hodge classes.  That
is the tropical Hodge question for this family, with the certificate neither stronger nor
weaker than it.  In particular the certificate is not a possibly-lossy sufficient condition:
if the Weil classes are tropically algebraic then no `Φ` exists, and conversely.

## The shape of the argument the statement invites

The values of `Φ` live in `MvPolynomial (Fin 10) ℚ`, a `ℚ`-vector space, so every quotient of
it by a subgroup is divisible and hence an injective `ℤ`-module.  The families that are
`Γ₁`-periodic in the vertex and invariant under rescaling of the direction are exactly the
`ℤ`-module maps out of the free `ℤ`-module on the *quotient* index set
`((Γ₂ ⊗ Γ_p)/Γ₁) × P(Γ₂ ⊗ ℚ) × Fin 6`; freeness on one side and injectivity on the other is
what makes the extension unobstructed.  That is the content of the answer, and it is why the
obstruction the soundness module worried about does not arise.

`triPhi`, `triRHS`, `parPhi`, `parRHS`, `Cell`, `cellPhi`, `cellVol`, `cellPrim` and
`cellDefect` are `KontsevichPhiSoundness`'s definitions verbatim; `gammaGen`, `gammaOne` and
`primBiv` are the root statement's verbatim; `Admissible` is
`KontsevichPhiSoundnessPeriodic`'s.

## What is asked, and what is not

**Asked.**  For every `d` and every submodule `L`: the implication above.

**Not asked, and not implied.**  Whether any chain has nonzero class; whether `Ξ_d` is a proper
sublattice for any `d`; the existence of any admissible `Φ`; anything about `θ`, `w₁`, `w₂`
themselves; the specialisation to complex abelian fourfolds; and the Hodge conjecture.
-/

namespace Statements.KontsevichPhiCompleteness

set_option maxHeartbeats 2000000
set_option maxRecDepth 20000

open MvPolynomial

abbrev T : Type := MvPolynomial (Fin 10) ℚ

noncomputable def pv : Fin 4 → T := ![X 0, X 1, X 2, X 3]

noncomputable def bv : Fin 6 → T := ![X 4, X 5, X 6, X 7, X 8, X 9]

abbrev G2 : Type := Fin 4 → ℤ

abbrev Gp : Type := Fin 4 → ℤ

abbrev G2P : Type := Fin 4 → Fin 4 → ℤ

def bivFst : Fin 6 → Fin 4 := ![0, 0, 0, 1, 1, 2]

def bivSnd : Fin 6 → Fin 4 := ![1, 2, 3, 2, 3, 3]

def wedge (u v : G2) (k : Fin 6) : ℤ :=
  u (bivFst k) * v (bivSnd k) - u (bivSnd k) * v (bivFst k)

noncomputable def wedgePoly (u v : G2) : T := ∑ k : Fin 6, ((wedge u v k : ℤ) : ℚ) • bv k

noncomputable def parPoly (s : Gp) : T := ∑ k : Fin 4, ((s k : ℤ) : ℚ) • pv k

noncomputable def rowPoly (A : G2P) (i : Fin 4) : T := ∑ m : Fin 4, ((A i m : ℤ) : ℚ) • pv m

def outer (u : G2) (s : Gp) : G2P := fun i k => u i * s k

noncomputable def app (Φ : G2P → G2 → Fin 6 → T) (x : G2P) (u : G2) (β : Fin 6 → ℤ) : T :=
  ∑ k : Fin 6, ((β k : ℤ) : ℚ) • Φ x u k

noncomputable def triDefect (Φ : G2P → G2 → Fin 6 → T) (x : G2P) (s : Gp) (u v : G2) : T :=
  app Φ x u (wedge u v) - app Φ x v (wedge u v)
    + app Φ (x + outer u s) (u - v) (wedge u v)
    - app Φ (x + outer u s) u (wedge u v)
    + app Φ (x + outer v s) v (wedge u v)
    - app Φ (x + outer v s) (u - v) (wedge u v)
    - parPoly s ^ 2 * wedgePoly u v ^ 2

noncomputable def parDefect (Φ : G2P → G2 → Fin 6 → T) (x : G2P) (s t : Gp) (u v : G2) : T :=
  app Φ x u (wedge u v) - app Φ x v (wedge u v)
    + app Φ (x + outer u s) v (wedge u v)
    - app Φ (x + outer u s) u (wedge u v)
    - app Φ (x + outer v t) u (wedge u v)
    + app Φ (x + outer v t) v (wedge u v)
    + app Φ (x + outer u s + outer v t) u (wedge u v)
    - app Φ (x + outer u s + outer v t) v (wedge u v)
    - (2 : ℚ) • (parPoly s * parPoly t * wedgePoly u v ^ 2)

/-- A triangle instance: vertex, parameter vector, two directions. -/
abbrev TriInst : Type := G2P × Gp × G2 × G2

/-- A parallelogram instance: vertex, two parameter vectors, two directions. -/
abbrev ParInst : Type := G2P × Gp × Gp × G2 × G2

/-- The `Φ`-side of Zharkov's triangle relation (1). -/
noncomputable def triPhi (Φ : G2P → G2 → Fin 6 → T) (e : TriInst) : T :=
  app Φ e.1 e.2.2.1 (wedge e.2.2.1 e.2.2.2) - app Φ e.1 e.2.2.2 (wedge e.2.2.1 e.2.2.2)
    + app Φ (e.1 + outer e.2.2.1 e.2.1) (e.2.2.1 - e.2.2.2) (wedge e.2.2.1 e.2.2.2)
    - app Φ (e.1 + outer e.2.2.1 e.2.1) e.2.2.1 (wedge e.2.2.1 e.2.2.2)
    + app Φ (e.1 + outer e.2.2.2 e.2.1) e.2.2.2 (wedge e.2.2.1 e.2.2.2)
    - app Φ (e.1 + outer e.2.2.2 e.2.1) (e.2.2.1 - e.2.2.2) (wedge e.2.2.1 e.2.2.2)

/-- The right-hand side of Zharkov's triangle relation (1): `s² ⊗ (u ∧ v)²`. -/
noncomputable def triRHS (e : TriInst) : T :=
  parPoly e.2.1 ^ 2 * wedgePoly e.2.2.1 e.2.2.2 ^ 2

/-- The `Φ`-side of Zharkov's parallelogram relation (2). -/
noncomputable def parPhi (Φ : G2P → G2 → Fin 6 → T) (e : ParInst) : T :=
  app Φ e.1 e.2.2.2.1 (wedge e.2.2.2.1 e.2.2.2.2)
    - app Φ e.1 e.2.2.2.2 (wedge e.2.2.2.1 e.2.2.2.2)
    + app Φ (e.1 + outer e.2.2.2.1 e.2.1) e.2.2.2.2 (wedge e.2.2.2.1 e.2.2.2.2)
    - app Φ (e.1 + outer e.2.2.2.1 e.2.1) e.2.2.2.1 (wedge e.2.2.2.1 e.2.2.2.2)
    - app Φ (e.1 + outer e.2.2.2.2 e.2.2.1) e.2.2.2.1 (wedge e.2.2.2.1 e.2.2.2.2)
    + app Φ (e.1 + outer e.2.2.2.2 e.2.2.1) e.2.2.2.2 (wedge e.2.2.2.1 e.2.2.2.2)
    + app Φ (e.1 + outer e.2.2.2.1 e.2.1 + outer e.2.2.2.2 e.2.2.1) e.2.2.2.1
        (wedge e.2.2.2.1 e.2.2.2.2)
    - app Φ (e.1 + outer e.2.2.2.1 e.2.1 + outer e.2.2.2.2 e.2.2.1) e.2.2.2.2
        (wedge e.2.2.2.1 e.2.2.2.2)

/-- The right-hand side of Zharkov's parallelogram relation (2): `2st ⊗ (u ∧ v)²`. -/
noncomputable def parRHS (e : ParInst) : T :=
  (2 : ℚ) • (parPoly e.2.1 * parPoly e.2.2.1 * wedgePoly e.2.2.2.1 e.2.2.2.2 ^ 2)

/-- One cell of a chain: a triangle or a parallelogram. -/
abbrev Cell : Type := TriInst ⊕ ParInst

/-- The `Φ`-side of a cell's relation. -/
noncomputable def cellPhi (Φ : G2P → G2 → Fin 6 → T) : Cell → T
  | Sum.inl e => triPhi Φ e
  | Sum.inr e => parPhi Φ e

/-- The tautological class of a cell: the right-hand side of its relation. -/
noncomputable def cellVol : Cell → T
  | Sum.inl e => triRHS e
  | Sum.inr e => parRHS e

/-- `u ∧ v` is a primitive vector of `⋀²Γ₂`. -/
def primBiv (u v : G2) : Prop := Finset.univ.gcd (wedge u v) = 1

/-- A cell is admissible when its two directions span a primitive bivector. -/
def cellPrim : Cell → Prop
  | Sum.inl e => primBiv e.2.2.1 e.2.2.2
  | Sum.inr e => primBiv e.2.2.2.1 e.2.2.2.2

/-- The defect of a cell's relation: the root statement's `triDefect` / `parDefect`. -/
noncomputable def cellDefect (Φ : G2P → G2 → Fin 6 → T) (z : Cell) : T :=
  cellPhi Φ z - cellVol z

/-- The four columns of Zharkov's polarisation matrix `Q`, read as elements of `Γ₂ ⊗ Γ_p`. -/
def gammaGen (d : ℤ) : Fin 4 → G2P :=
  ![ ![![1, 0, 0, 0], ![0, 1, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 1]],
     ![![0, 1, 0, 0], ![0, 0, 1, 0], ![0, 0, 0, -1], ![0, 0, 0, 0]],
     ![![0, 0, 0, 0], ![0, 0, 0, -1], ![d, 0, 0, 0], ![0, d, 0, 0]],
     ![![0, 0, 0, 1], ![0, 0, 0, 0], ![0, d, 0, 0], ![0, 0, d, 0]] ]

/-- The period lattice `Γ₁ ⊆ Γ₂ ⊗ Γ_p`. -/
noncomputable def gammaOne (d : ℤ) : Submodule ℤ G2P :=
  Submodule.span ℤ (Set.range (gammaGen d))

/-- A family is *admissible* when it is `Γ₁`-periodic in the vertex and invariant under
nonzero integer rescaling of the direction — exactly the two side conditions the root
statement imposes on `Φ`. -/
def Admissible (d : ℤ) (Ψ : G2P → G2 → Fin 6 → T) : Prop :=
  (∀ (x : G2P) (u : G2) (g : G2P), g ∈ gammaOne d → Ψ (x + g) u = Ψ x u) ∧
    (∀ (x : G2P) (u : G2) (m : ℤ), m ≠ 0 → Ψ x (m • u) = Ψ x u)

/-- The canonical proposition.  Completeness of Kontsevich's certificate. -/
abbrev statement : Prop :=
  ∀ (d : ℤ) (L : Submodule ℤ T),
    (∀ (ι : Type) (s : Finset ι) (c : ι → ℤ) (z : ι → Cell),
        (∀ i ∈ s, cellPrim (z i)) →
        (∀ Ψ : G2P → G2 → Fin 6 → T, Admissible d Ψ →
            ∑ i ∈ s, (c i : T) * cellPhi Ψ (z i) = 0) →
        ∑ i ∈ s, (c i : T) * cellVol (z i) ∈ L) →
    ∃ Φ : G2P → G2 → Fin 6 → T, Admissible d Φ ∧
      ∀ z : Cell, cellPrim z → cellDefect Φ z ∈ L

/-- The open target.  A submission proves `statement` in its own module; the verifier
bridges the two. -/
theorem target : statement := sorry

end Statements.KontsevichPhiCompleteness
