import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.Data.Fin.VecNotation
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Algebra.GCDMonoid.Finset

/-!
# KontsevichPhiIffContained — the root question is a pure containment

Self-contained: imports only `Mathlib`, defines everything it mentions, uses no `Commons`.

`rootProp` is `Statements.KontsevichWeilPhi.statement` restated character for character, and
`Ξ_d` (`Xi`) is the subgroup generated by the tautological classes of the chains balanced over
admissible families — `Γ₁(d)`-periodic in the vertex and invariant under rescaling of the
direction — which is the group of classes of tropical cycles in the encoding this problem
uses.  `KontsevichPhiIffLattice` establishes

  root  ⟺  `∃ d > 0` with `Ξ_d` a **proper** subgroup of `ℤ⟨θ, w₁, w₂⟩`,

with proper meaning contained **and** distinct.  This statement drops the "and distinct":

  root  ⟺  `∃ d > 0` with `Ξ_d ≤ ℤ⟨θ, w₁, w₂⟩`.

## Why the two halves of "proper" are not equally hard

Distinctness is free, and this statement is the observation that it is.  Every cell's
tautological class is `s² ⊗ (u ∧ v)²` or `2st ⊗ (u ∧ v)²`; evaluating at `a = α`, `c = γ`,
`b = e = x₁₃ = x₁₄ = x₂₃ = x₂₄ = x₃₄ = 0`, `x₁₂ = 1` and taking `f(1,1) - f(1,0) - f(0,1)`
reads off the coefficient of `a·c·x₁₂²`, which is `2 s₀s₂ w₀²` on a triangle and
`2(s₀t₂ + s₂t₀) w₀²` on a parallelogram — even in both cases, hence even on every
`ℤ`-combination and so on all of `Ξ_d`.  On `θ` the same functional is `1`.  So `θ ∉ Ξ_d` for
every `d`, and `Ξ_d` can never be all of `ℤ⟨θ, w₁, w₂⟩`.  (`KontsevichVolParity` records the
same evenness in the form `n₁ + n₂` even.)

Containment is the whole question.  What is left of Kontsevich's proposal, with soundness and
completeness both in hand, is exactly:

  **is every tautological class of a tropical cycle an integral combination of `θ`, `w₁`,
  `w₂`?**

If yes for some `d > 0` the obstruction exists, and by `KontsevichPhiSoundnessPeriodic` it
certifies that `θ` — and whatever else of `ℤ⟨θ, w₁, w₂⟩ ∖ Ξ_d` — is not a tropical cycle
class.  If no for every `d`, some chain has a class outside the Weil lattice and Kontsevich's
certificate does not exist.

## What is claimed, and what is not

**Claimed.**  The biconditional.

**Not claimed.**  Which side holds; any computation of `Ξ_d`; the existence of a chain with
nonzero class; the identification of `Ξ_d` with classes of geometric tropical cycles, which is
argued above and not formalised; the specialisation to complex abelian fourfolds; the Hodge
conjecture.
-/

namespace Statements.KontsevichPhiIffContained

set_option maxHeartbeats 2000000
set_option maxRecDepth 20000

open MvPolynomial

abbrev T : Type := MvPolynomial (Fin 10) ℚ

noncomputable def pv : Fin 4 → T := ![X 0, X 1, X 2, X 3]

noncomputable def bv : Fin 6 → T := ![X 4, X 5, X 6, X 7, X 8, X 9]

abbrev G2 : Type := Fin 4 → ℤ

abbrev Gp : Type := Fin 4 → ℤ

abbrev G2P : Type := Fin 4 → Fin 4 → ℤ

def bivFst : Fin 6 → Fin 4 := ![0, 0, 0, 1, 1, 2]

def bivSnd : Fin 6 → Fin 4 := ![1, 2, 3, 2, 3, 3]

def wedge (u v : G2) (k : Fin 6) : ℤ :=
  u (bivFst k) * v (bivSnd k) - u (bivSnd k) * v (bivFst k)

noncomputable def wedgePoly (u v : G2) : T := ∑ k : Fin 6, ((wedge u v k : ℤ) : ℚ) • bv k

noncomputable def parPoly (s : Gp) : T := ∑ k : Fin 4, ((s k : ℤ) : ℚ) • pv k

noncomputable def rowPoly (A : G2P) (i : Fin 4) : T := ∑ m : Fin 4, ((A i m : ℤ) : ℚ) • pv m

def outer (u : G2) (s : Gp) : G2P := fun i k => u i * s k

noncomputable def app (Φ : G2P → G2 → Fin 6 → T) (x : G2P) (u : G2) (β : Fin 6 → ℤ) : T :=
  ∑ k : Fin 6, ((β k : ℤ) : ℚ) • Φ x u k

noncomputable def triDefect (Φ : G2P → G2 → Fin 6 → T) (x : G2P) (s : Gp) (u v : G2) : T :=
  app Φ x u (wedge u v) - app Φ x v (wedge u v)
    + app Φ (x + outer u s) (u - v) (wedge u v)
    - app Φ (x + outer u s) u (wedge u v)
    + app Φ (x + outer v s) v (wedge u v)
    - app Φ (x + outer v s) (u - v) (wedge u v)
    - parPoly s ^ 2 * wedgePoly u v ^ 2

noncomputable def parDefect (Φ : G2P → G2 → Fin 6 → T) (x : G2P) (s t : Gp) (u v : G2) : T :=
  app Φ x u (wedge u v) - app Φ x v (wedge u v)
    + app Φ (x + outer u s) v (wedge u v)
    - app Φ (x + outer u s) u (wedge u v)
    - app Φ (x + outer v t) u (wedge u v)
    + app Φ (x + outer v t) v (wedge u v)
    + app Φ (x + outer u s + outer v t) u (wedge u v)
    - app Φ (x + outer u s + outer v t) v (wedge u v)
    - (2 : ℚ) • (parPoly s * parPoly t * wedgePoly u v ^ 2)

/-- A triangle instance: vertex, parameter vector, two directions. -/
abbrev TriInst : Type := G2P × Gp × G2 × G2

/-- A parallelogram instance: vertex, two parameter vectors, two directions. -/
abbrev ParInst : Type := G2P × Gp × Gp × G2 × G2

/-- The `Φ`-side of Zharkov's triangle relation (1). -/
noncomputable def triPhi (Φ : G2P → G2 → Fin 6 → T) (e : TriInst) : T :=
  app Φ e.1 e.2.2.1 (wedge e.2.2.1 e.2.2.2) - app Φ e.1 e.2.2.2 (wedge e.2.2.1 e.2.2.2)
    + app Φ (e.1 + outer e.2.2.1 e.2.1) (e.2.2.1 - e.2.2.2) (wedge e.2.2.1 e.2.2.2)
    - app Φ (e.1 + outer e.2.2.1 e.2.1) e.2.2.1 (wedge e.2.2.1 e.2.2.2)
    + app Φ (e.1 + outer e.2.2.2 e.2.1) e.2.2.2 (wedge e.2.2.1 e.2.2.2)
    - app Φ (e.1 + outer e.2.2.2 e.2.1) (e.2.2.1 - e.2.2.2) (wedge e.2.2.1 e.2.2.2)

/-- The right-hand side of Zharkov's triangle relation (1): `s² ⊗ (u ∧ v)²`. -/
noncomputable def triRHS (e : TriInst) : T :=
  parPoly e.2.1 ^ 2 * wedgePoly e.2.2.1 e.2.2.2 ^ 2

/-- The `Φ`-side of Zharkov's parallelogram relation (2). -/
noncomputable def parPhi (Φ : G2P → G2 → Fin 6 → T) (e : ParInst) : T :=
  app Φ e.1 e.2.2.2.1 (wedge e.2.2.2.1 e.2.2.2.2)
    - app Φ e.1 e.2.2.2.2 (wedge e.2.2.2.1 e.2.2.2.2)
    + app Φ (e.1 + outer e.2.2.2.1 e.2.1) e.2.2.2.2 (wedge e.2.2.2.1 e.2.2.2.2)
    - app Φ (e.1 + outer e.2.2.2.1 e.2.1) e.2.2.2.1 (wedge e.2.2.2.1 e.2.2.2.2)
    - app Φ (e.1 + outer e.2.2.2.2 e.2.2.1) e.2.2.2.1 (wedge e.2.2.2.1 e.2.2.2.2)
    + app Φ (e.1 + outer e.2.2.2.2 e.2.2.1) e.2.2.2.2 (wedge e.2.2.2.1 e.2.2.2.2)
    + app Φ (e.1 + outer e.2.2.2.1 e.2.1 + outer e.2.2.2.2 e.2.2.1) e.2.2.2.1
        (wedge e.2.2.2.1 e.2.2.2.2)
    - app Φ (e.1 + outer e.2.2.2.1 e.2.1 + outer e.2.2.2.2 e.2.2.1) e.2.2.2.2
        (wedge e.2.2.2.1 e.2.2.2.2)

/-- The right-hand side of Zharkov's parallelogram relation (2): `2st ⊗ (u ∧ v)²`. -/
noncomputable def parRHS (e : ParInst) : T :=
  (2 : ℚ) • (parPoly e.2.1 * parPoly e.2.2.1 * wedgePoly e.2.2.2.1 e.2.2.2.2 ^ 2)

/-- One cell of a chain: a triangle or a parallelogram. -/
abbrev Cell : Type := TriInst ⊕ ParInst

/-- The `Φ`-side of a cell's relation. -/
noncomputable def cellPhi (Φ : G2P → G2 → Fin 6 → T) : Cell → T
  | Sum.inl e => triPhi Φ e
  | Sum.inr e => parPhi Φ e

/-- The tautological class of a cell: the right-hand side of its relation. -/
noncomputable def cellVol : Cell → T
  | Sum.inl e => triRHS e
  | Sum.inr e => parRHS e

/-- `u ∧ v` is a primitive vector of `⋀²Γ₂`. -/
def primBiv (u v : G2) : Prop := Finset.univ.gcd (wedge u v) = 1

/-- A cell is admissible when its two directions span a primitive bivector. -/
def cellPrim : Cell → Prop
  | Sum.inl e => primBiv e.2.2.1 e.2.2.2
  | Sum.inr e => primBiv e.2.2.2.1 e.2.2.2.2

/-- The defect of a cell's relation: the root statement's `triDefect` / `parDefect`. -/
noncomputable def cellDefect (Φ : G2P → G2 → Fin 6 → T) (z : Cell) : T :=
  cellPhi Φ z - cellVol z

/-- The four columns of Zharkov's polarisation matrix `Q`, read as elements of `Γ₂ ⊗ Γ_p`. -/
def gammaGen (d : ℤ) : Fin 4 → G2P :=
  ![ ![![1, 0, 0, 0], ![0, 1, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 1]],
     ![![0, 1, 0, 0], ![0, 0, 1, 0], ![0, 0, 0, -1], ![0, 0, 0, 0]],
     ![![0, 0, 0, 0], ![0, 0, 0, -1], ![d, 0, 0, 0], ![0, d, 0, 0]],
     ![![0, 0, 0, 1], ![0, 0, 0, 0], ![0, d, 0, 0], ![0, 0, d, 0]] ]

/-- The period lattice `Γ₁ ⊆ Γ₂ ⊗ Γ_p`. -/
noncomputable def gammaOne (d : ℤ) : Submodule ℤ G2P :=
  Submodule.span ℤ (Set.range (gammaGen d))

/-- A family is *admissible* when it is `Γ₁`-periodic in the vertex and invariant under
nonzero integer rescaling of the direction — exactly the two side conditions the root
statement imposes on `Φ`. -/
def Admissible (d : ℤ) (Ψ : G2P → G2 → Fin 6 → T) : Prop :=
  (∀ (x : G2P) (u : G2) (g : G2P), g ∈ gammaOne d → Ψ (x + g) u = Ψ x u) ∧
    (∀ (x : G2P) (u : G2) (m : ℤ), m ≠ 0 → Ψ x (m • u) = Ψ x u)

/-! ## The root statement, restated verbatim -/

/-- The projection of `A ∧ B` to `Sym²Γ_p ⊗ ⋀²Γ₂`. -/
noncomputable def wedgeMat (A B : G2P) : T :=
  ∑ k : Fin 6,
    (rowPoly A (bivFst k) * rowPoly B (bivSnd k) - rowPoly A (bivSnd k) * rowPoly B (bivFst k))
      * bv k

/-- `θ`, the square of the polarisation. -/
noncomputable def theta (d : ℤ) : T :=
  ∑ k : Fin 6, wedgeMat (gammaGen d (bivFst k)) (gammaGen d (bivSnd k)) * bv k

/-- The first Weil class. -/
noncomputable def w1 (d : ℤ) : T :=
  let g := gammaGen d
  wedgeMat (g 0) (g 1) * bv 0
    - (1 / (d : ℚ)) • (wedgeMat (g 2) (g 3) * bv 0)
    - wedgeMat (g 0) (g 3) * bv 2
    + wedgeMat (g 0) (g 3) * bv 3
    + wedgeMat (g 1) (g 2) * bv 2
    - wedgeMat (g 1) (g 2) * bv 3
    - (d : ℚ) • (wedgeMat (g 0) (g 1) * bv 5)
    + wedgeMat (g 2) (g 3) * bv 5

/-- The second Weil class. -/
noncomputable def w2 (d : ℤ) : T :=
  let g := gammaGen d
  wedgeMat (g 0) (g 3) * bv 0
    - (d : ℚ) • (wedgeMat (g 0) (g 3) * bv 5)
    - (d : ℚ) • (wedgeMat (g 0) (g 1) * bv 3)
    + wedgeMat (g 2) (g 3) * bv 3
    + (d : ℚ) • (wedgeMat (g 0) (g 1) * bv 2)
    - wedgeMat (g 2) (g 3) * bv 2
    - wedgeMat (g 1) (g 2) * bv 0
    + (d : ℚ) • (wedgeMat (g 1) (g 2) * bv 5)

/-- The lattice `ℤ⟨θ, w₁, w₂⟩`. -/
noncomputable def weilLattice (d : ℤ) : Submodule ℤ T :=
  Submodule.span ℤ {theta d, w1 d, w2 d}

/-- The root statement of this problem, `KontsevichWeilPhi.statement`, restated verbatim. -/
abbrev rootProp : Prop :=
  ∃ d : ℤ, 0 < d ∧
    ∃ (L : Submodule ℤ T) (Φ : G2P → G2 → Fin 6 → T),
      L < weilLattice d ∧
      (∀ (x : G2P) (u : G2) (g : G2P), g ∈ gammaOne d → Φ (x + g) u = Φ x u) ∧
      (∀ (x : G2P) (u : G2) (m : ℤ), m ≠ 0 → Φ x (m • u) = Φ x u) ∧
      (∀ (x : G2P) (s : Gp) (u v : G2), primBiv u v → triDefect Φ x s u v ∈ L) ∧
      (∀ (x : G2P) (s t : Gp) (u v : G2), primBiv u v → parDefect Φ x s t u v ∈ L)

/-! ## The lattice of tautological classes -/

/-- The tautological class of a chain balanced over admissible families. -/
def chainClass (d : ℤ) : Set T :=
  { y | ∃ (ι : Type) (s : Finset ι) (c : ι → ℤ) (z : ι → Cell),
      (∀ i ∈ s, cellPrim (z i)) ∧
      (∀ Ψ : G2P → G2 → Fin 6 → T, Admissible d Ψ →
        ∑ i ∈ s, (c i : T) * cellPhi Ψ (z i) = 0) ∧
      y = ∑ i ∈ s, (c i : T) * cellVol (z i) }

/-- `Ξ_d`, the subgroup generated by those classes. -/
noncomputable def Xi (d : ℤ) : Submodule ℤ T := Submodule.span ℤ (chainClass d)

/-- The canonical proposition.  This is the type the verifier demands.

Kontsevich's obstruction exists if and only if, for some `d > 0`, every tautological class of
a chain balanced over admissible families is an integral combination of `θ`, `w₁` and `w₂`. -/
abbrev statement : Prop :=
  rootProp ↔ ∃ d : ℤ, 0 < d ∧ Xi d ≤ weilLattice d

/-- The open target.  A submission proves `statement` in its own module; the verifier
bridges the two. -/
theorem target : statement := sorry

end Statements.KontsevichPhiIffContained
