import Mathlib.Analysis.SpecialFunctions.Sqrt
import Commons.PaleyLocalizationTheta

/-!
# PaleyLocThetaProduct — Lovász's `ϑ(G)ϑ(Ḡ) = n` for the Paley 1-localization

`Commons.paleyLocTheta p` is `ϑ(Ḡ_{p,1})`, the clique-bounding side.  `coTheta p` below is
`ϑ(G_{p,1})`, the independence-bounding side: `thetaClique` of the *complement* adjacency.

`G_{p,1}` is vertex-transitive — the multiplicative group of nonzero squares of `ZMod p` acts
on the vertex set `Q` by `u ↦ su`, this preserves `paleyLocAdj` because `s(u-v)` is a nonzero
square exactly when `u-v` is, and it is simply transitive on `Q`.  Lovász (*On the Shannon
capacity of a graph*, IEEE Trans. Inform. Theory 25 (1979) 1–7, Theorem 8) proves
`ϑ(G)ϑ(Ḡ) = n` for every vertex-transitive graph, and here `n = |Q| = (p-1)/2`.

This statement is that identity, specialised.  It is the missing input of
`Statements.PaleyLocSelfDualReduction`: with it, an upper bound on either theta is a lower
bound on the other, which is exactly why the published window `[½√p, √p]` on
`ϑ(Ḡ_{p,1})` is generated by a single elementary fact applied to a graph and to its
complement.  It is filed unproved and labelled so that a proof can be checked against it.
-/

namespace Statements.PaleyLocThetaProduct

/-- `ϑ(G_{p,1})`: `thetaClique` of the complement adjacency of the Paley 1-localization. -/
noncomputable def coTheta (p : ℕ) (hp : 0 < p) : ℝ :=
  haveI : NeZero p := NeZero.of_pos hp
  Commons.thetaClique (fun u v : Commons.PaleyLocV p => u ≠ v ∧ ¬ Commons.paleyLocAdj p u v)

/-- The canonical proposition: `ϑ(Ḡ_{p,1}) · ϑ(G_{p,1}) = (p-1)/2`. -/
abbrev statement : Prop :=
  ∀ p : ℕ, ∀ hp : Nat.Prime p, p % 4 = 1 →
    Commons.paleyLocTheta p hp.pos * coTheta p hp.pos = ((p : ℝ) - 1) / 2

theorem target : statement := sorry

end Statements.PaleyLocThetaProduct
