import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.Data.Fin.VecNotation
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Algebra.GCDMonoid.Finset

/-!
# TropicalNS — the (1,1) tropical Hodge classes of Zharkov's family are exactly `ℤ·c`

Self-contained: imports only `Mathlib`, defines everything it mentions, uses no `Commons`.

## What this says

`H_1(X, F_1) = Γ₁ ⊗ Γ₂`, and an element of it is `ξ = ∑_l γ_l ⊗ v_l` with `v_l ∈ Γ₂`.  Viewing
`Γ₁ ⊆ Γ₂ ⊗ Γ_p`, such a `ξ` becomes a `Γ_p`-valued square matrix in the two `Γ₂` indices, and
`EigenwaveKernelPolarisation` (p/8?s=7) is the statement that the tautological class
`c = ∑_l γ_l ⊗ e_l` lies in the kernel of the eigenwave *because* `Q` is symmetric.  The
kernel of the eigenwave at `p = 1` is exactly the symmetry of that matrix.  This statement is
the converse and the exact count:

  the only `ξ ∈ Γ₁ ⊗ Γ₂` with symmetric matrix are the integer multiples of `c`.

So the Néron–Severi group of the whole four-parameter family — the classes that stay Hodge for
every `a, b, c, e` — is `ℤ·c`, of rank one, for every `d > 0`.

## Why it sits on this problem

`KontsevichPhiIffContained` (p/8?s=17) makes the root question exactly `Ξ_d ⊆ ℤ⟨θ, w₁, w₂⟩`,
where `Ξ_d` is generated by the tautological classes of balanced chains, and
`KontsevichChainVolVanishes` (p/8?s=12) says every nonzero element of `Ξ_d` comes from a chain
that wraps.  The cheapest way to build a wrapping 2-chain is a **Pontryagin product**: take two
tropical curves `C`, `C'` in `X` and push `C × C'` forward along the group law.  That product
is balanced — at each flag the sum of the incident bivectors factors as
`u_e ∧ (∑_f ± u_f) = u_e ∧ 0 = 0` by the balancing of the other factor — so it is a legitimate
source of elements of `Ξ_d`, and it is the construction a search would try first.

This statement kills it.  A tropical curve `C` has `vol(C) = ∑_e w_e (u_e ⊗ s_e) ⊗ u_e`, which
is symmetric in its two `Γ₂` indices by inspection and lies in `Γ₁ ⊗ Γ₂` because each
`Γ₂`-component of `C` is an honest `1`-cycle; so `vol(C) = k·c` by this statement.  The class
of `C * C'` depends on `vol(C)` and `vol(C')` alone — it is the value of an explicit symmetric
bilinear pairing `B` on them, `B(N, N')` being `2 ∑_{k,l} x_k x_l (N_{i_k i_l} N'_{j_k j_l} -
N_{i_k j_l} N'_{j_k i_l} - N_{j_k i_l} N'_{i_k j_l} + N_{j_k j_l} N'_{i_k i_l})` — and
`B(kc, k'c) = 4kk'·θ`, because `B(c,c)` is four times the contraction of `⋀²Q` against
`x_k x_l`, which is `θ`.  So **every Pontryagin product of two tropical curves has tautological
class in `4ℤ·θ`**, and no such product can ever reach `w₁` or `w₂`, or `θ` itself.

The residual: elements of `Ξ_d` that are not products of curves.  Any construction must be a
2-chain that does not factor through the group law.  (This is consistent with, and sharper
than, `KontsevichVolParity` (p/8?s=15), which already forbids `θ` and `w₁` outright: `4θ` is
permitted by parity, and this statement says `4θ` is the *most* the product construction can
give.)

## What is proved here, and what is prose

Proved: the displayed statement about `ξ ∈ Γ₁ ⊗ Γ₂`, for every `d > 0`.  Prose, and not
proved here: that `vol(C)` of a tropical curve lies in `Γ₁ ⊗ Γ₂` and is symmetric, that the
Pontryagin product is balanced, and the identity `B(c,c) = 4θ` (verified symbolically, not in
Lean).  Those three are the bridge, and a contributor who wants the barrier machine-checked
end to end should formalise them; the arithmetic core, which is the part that could have gone
either way, is here.
-/

namespace Statements.TropicalNS

/-- The lattice `Γ₂` of integral slopes. -/
abbrev G2 : Type := Fin 4 → ℤ

/-- `Γ₂ ⊗ Γ_p`. -/
abbrev G2P : Type := Fin 4 → Fin 4 → ℤ

/-- The four columns of Zharkov's polarisation matrix `Q`, read as elements of `Γ₂ ⊗ Γ_p`.
They span `Γ₁`; `gammaGen d l i m` is the `m`-th parameter coordinate of the `i`-th `Γ₂`
coordinate of `γ_l`, which is the `(i,l)` entry of `Q`. -/
def gammaGen (d : ℤ) : Fin 4 → G2P :=
  ![ ![![1, 0, 0, 0], ![0, 1, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 1]],
     ![![0, 1, 0, 0], ![0, 0, 1, 0], ![0, 0, 0, -1], ![0, 0, 0, 0]],
     ![![0, 0, 0, 0], ![0, 0, 0, -1], ![d, 0, 0, 0], ![0, d, 0, 0]],
     ![![0, 0, 0, 1], ![0, 0, 0, 0], ![0, d, 0, 0], ![0, 0, d, 0]] ]

/-- The canonical proposition.  This is the type the verifier demands.

For every `d > 0`: if `ξ = ∑_l γ_l ⊗ v_l ∈ Γ₁ ⊗ Γ₂` has symmetric matrix in its two `Γ₂`
indices — the `(1,1)` Hodge condition — then `ξ` is an integer multiple of the tautological
class `c = ∑_l γ_l ⊗ e_l`. -/
abbrev statement : Prop :=
  ∀ (d : ℤ), 0 < d → ∀ (v : Fin 4 → G2),
    (∀ i j m : Fin 4,
        ∑ l : Fin 4, gammaGen d l i m * v l j = ∑ l : Fin 4, gammaGen d l j m * v l i) →
    ∃ k : ℤ, ∀ l j : Fin 4, v l j = if l = j then k else 0

/-- The open target.  A submission proves `statement` in its own module; the verifier
bridges the two. -/
theorem target : statement := sorry

end Statements.TropicalNS
